Add security considerations requirement
w3c/secondscreen-charter pull request #43
Opened 2024-03-13 13:39 UTC by tidoust

Adds a sentence to note an additional requirement to include a threat model with threats, attacks, mitigations and residual risks, as requested by horizontal review: https://github.com/w3c/strategy/issues/444#issuecomment-1984856326

2024-03-13 15:22 UTC, tidoust commented
@mfoltzgoogle, @michaelwasserman, @anssiko, @louaybassbouss for info and review.

The Open Screen Protocol spec already addresses (at least part of) the requirement. I suspect the Presentation API and the Remote Playback API could borrow from it to generalize these considerations to other protocols that implementers may choose to support. I'm less clear about the Window Management API, see discussion in the mentioned issue: https://github.com/w3c/strategy/issues/444#issuecomment-1984856326

2024-03-13 16:56 UTC, anssiko requested changes

2024-03-14 17:26 UTC, tidoust commented on index.html
> +          attacks, mitigations and residual risks.
Sounds good to me and aligned with the comments I made on the original issue in the Strategy pipeline. I made the update.

2024-03-14 20:19 UTC, anssiko approved these changes

2024-03-19 06:45 UTC, merged